[TASK] #84616 | Add currently online users information
TYPO3-Initiatives/adminpanel-extended pull request #3
Opened 2018-04-20 13:05 UTC by KamiYang

See here for detailed information: [#84616](https://forge.typo3.org/issues/84616)

2018-10-04 14:00 UTC, susannemoog requested changes
The interfaces changed, as well as the API. Please see the documentation / other modules and update accordingly.

2018-10-04 14:06 UTC, KamiYang commented
I'm currently on changing these things. Should have marked this PR as "WIP" :)

2018-10-09 21:30 UTC, susannemoog requested changes

2018-10-09 21:30 UTC, psychomieze commented on Classes/Modules/Info/UserInformation.php
> +        $frontendUserSessionReposiotry = GeneralUtility::makeInstance(ObjectManager::class)
fix typo in repository ;)

2018-10-10 09:48 UTC, susannemoog approved these changes

2018-10-10 09:48 UTC, merged